// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaBlue.Db;

#nullable disable

namespace ProvaBlue.Migrations
{
    [DbContext(typeof(Prova_db_context))]
    partial class Prova_db_contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaBlue.Models.ContatoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ervin_feil15@hotmail.com",
                            Nome = "Courtney Cummings",
                            Numero = "81-9-7864-4631"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jeanette39@gmail.com",
                            Nome = "Freddie Zieme",
                            Numero = "81-9-0955-4692"
                        },
                        new
                        {
                            Id = 3,
                            Email = "marc.lang82@gmail.com",
                            Nome = "Juan Quigley",
                            Numero = "81-9-6656-3599"
                        },
                        new
                        {
                            Id = 4,
                            Email = "andrew.hahn@hotmail.com",
                            Nome = "Clayton Legros",
                            Numero = "81-9-3612-7387"
                        },
                        new
                        {
                            Id = 5,
                            Email = "marcus7@hotmail.com",
                            Nome = "Kent Ullrich",
                            Numero = "81-9-5812-8613"
                        },
                        new
                        {
                            Id = 6,
                            Email = "agnes_okon@gmail.com",
                            Nome = "Harriet Windler",
                            Numero = "81-9-8787-9600"
                        },
                        new
                        {
                            Id = 7,
                            Email = "steve.gleason14@gmail.com",
                            Nome = "Elias Wisozk",
                            Numero = "81-9-9527-1612"
                        },
                        new
                        {
                            Id = 8,
                            Email = "wallace.rodriguez36@gmail.com",
                            Nome = "Tim Yundt",
                            Numero = "81-9-0864-6699"
                        },
                        new
                        {
                            Id = 9,
                            Email = "clayton.mcglynn98@yahoo.com",
                            Nome = "Hannah Bernier",
                            Numero = "81-9-4543-8012"
                        },
                        new
                        {
                            Id = 10,
                            Email = "andy_bergstrom@hotmail.com",
                            Nome = "Harry Cassin",
                            Numero = "81-9-6349-5168"
                        });
                });

            modelBuilder.Entity("ProvaBlue.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123",
                            Role = "BlueEmployee",
                            UserName = "felipe"
                        },
                        new
                        {
                            Id = 2,
                            Password = "321",
                            Role = "NotEmployee",
                            UserName = "marcio"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
